config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#home'
  get 'dashboard' => 'dashboards#index'

  get 'dashboard/projects' => 'dashboards#projects'
  resources :projects
  resources :accounts
  resources :reviews
  resources :issues


  resources :accounts do
    member do
      get :sync_reviews
    end
  end

   resources :projects do
    member do
      get :sync_issues
    end
  end
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :project

  validates :title, presence: true
  validates :uid, presence: true, uniqueness: { scope: :project }
  validates :issue_url, presence: true

  def self.sync(params)
    issue = Issue.where(project_id: params[:project_id], uid: params[:uid]).first_or_initialize
    issue.assign_attributes(
      title: params[:title],
      description: params[:description],
    )
    issue.issue_url = params[:issue_url] if params[:issue_url].present?

    issue.save! if issue.new_record? || issue.changed?
    issue
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  layout 'dashboard/main'
  # GET /issues
  def index
    @issues = current_user.issues
  end

  # GET /issues/1
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      redirect_to @issue, notice: 'Issue was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /issues/1
  def update
    if @issue.update(issue_params)
      redirect_to @issue, notice: 'Issue was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /issues/1
  def destroy
    @issue.destroy
    redirect_to issues_url, notice: 'Issue was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def issue_params
      params.require(:issue).permit(:title, :description, :issue_url)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for(issue) do |f| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :issue_url %>
    <%= f.text_field :issue_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Issues</h3>
  <div class="row">

    <% @issues.each_with_index do |issue, i| %>
      <% if(i != 0 && i % 3 == 0)  %>
        <div class="row">
      <% end %>
        <%= link_to issue do %>
          <div class="col-sm-3 panel issue-box"><%= truncate(issue.title, length: 90) %></div>
        <% end %>
      <% if(i != 0 && ((i+1) % 3 == 0)) %>
        </div>
      <% end %>
    <% end %>
  </div>
<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @issue.description %>
</p>

<p>
  <strong>Issue url:</strong>
  <%= link_to('link', @issue.issue_url) %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>