config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#home'
  get 'dashboard' => 'dashboards#index'

  get 'dashboard/projects' => 'dashboards#projects'
  resources :projects
  resources :accounts
  resources :reviews
  resources :issues


  resources :accounts do
    member do
      get :sync_reviews
    end
  end

   resources :projects do
    member do
      get :sync_issues
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  validates :slug, presence: true, uniqueness: true

  belongs_to :user
  has_many :accounts, dependent: :destroy
  has_many :issues, dependent: :destroy

  before_validation :set_slug

  def set_slug
    self.slug = name.strip.downcase.parameterize if name.present?
  end

  def primary_account
    return unless accounts.present?
    if accounts.android.present?
      accounts.android.first
    else
      accounts.first
    end
  end

  def sync_issues
    return unless trello_board_uid.present?
    trello_client = TrelloUtils.new
    remote_issues = trello_client.fetch_cards(self)
    remote_issues.each do |remote_issue|
      Issue.sync(remote_issue)
    end
    issues
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout 'dashboard/main'
  before_action :set_project, only: [:show, :edit, :update, :destroy, :sync_issues]

  # GET /projects
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def sync_issues
    @project.sync_issues
      redirect_to @project, notice: 'Project was successfully synced.'

  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, :slug, :user, :trello_board_uid, :created_at, :updated_at).merge(user_id: current_user.id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label :trello_board_uid %>
    <%= f.text_field :trello_board_uid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

  <% @projects.each_with_index do |project, i| %>
      <% if(project.accounts.present?) %>
        <%= link_to image_tag(project.primary_account.display_picture_url, class: 'img-rounded project-thumb'),project %>
      <% else %>
        <%= link_to project do %>
          <i class="fa fa-folder fa-4x img-rounded project-thumb"></i>
        <% end %>
      <% end %>
   <!--  <tr>
      <td><%= project.name %></td>
      <td><%= project.slug %></td>
      <td><%= project.trello_board_uid %></td> -->
     <!--  <td><%= link_to 'Show', project %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
    </tr>
  <% end %>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @project.slug %>
</p>

<p>
  <strong>Trello board</strong>
  <%= @project.trello_board_uid %>
</p>
</br>
<h4>Linked accounts</h4>
   <% count = @project.accounts.count %>

  <% @project.accounts.each_with_index do |account, i| %>
    <%= link_to account do %>
      <% if(i % 2 == 1 || i == 0) %>
        <div class="row">
      <% end %>
          <div class="well col-md-4 account-show-panel">
            <div class="col-md-4">
              <% if account.android? %>
                <i class="fa fa-android fa-4x" style="color:#A4C639" aria-hidden="true"></i>
              <% elsif account.twitter? %>
                <i class="fa fa-twitter fa-4x" style="color:#0084b4" aria-hidden="true"></i>
              <% end %>
            </div>
            <div class="col-md-8">
              <p class="row"><%= account.name %></p>
              <p class="row"><%= account.uid %></p>
            </div>
          </div>

        <% if((i % 2 == 1) || (i == (count -1))) %>
          </div>
        <% end %>
    <% end %>
<% end %>
</br>
<%= link_to 'Sync Issues', sync_issues_project_path(@project) %> |
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
</br>

<% if @project.trello_board_uid.present? %>
  <h4>Linked Issue tracker</h4>
    <div class="row">

      <% @project.issues.each_with_index do |issue, i| %>
        <% if(i != 0 && i % 3 == 0)  %>
          <div class="row">
        <% end %>
          <%= link_to issue do %>
            <div class="col-sm-3 panel issue-box"><%= truncate(issue.title, length: 90) %></div>
          <% end %>
        <% if(i != 0 && ((i+1) % 3 == 0)) %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</br>