config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#home'
  get 'dashboard' => 'dashboards#index'

  get 'dashboard/projects' => 'dashboards#projects'
  resources :projects
  resources :accounts
  resources :reviews
  resources :issues


  resources :accounts do
    member do
      get :sync_reviews
    end
  end

   resources :projects do
    member do
      get :sync_issues
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  layout 'dashboard/main'
  
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to @review, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /reviews/1
  def update
    if @review.update(review_params)
      redirect_to @review, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reviews/1
  def destroy
    @review.destroy
    redirect_to reviews_url, notice: 'Review was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def review_params
      params.require(:review).permit(:title, :description, :rating, :author)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(review) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.text_field :rating %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row" style="text-align: left">
  <% if @reviews.first.account.android? %>
    <i class="fa fa-android fa-4x" style="color:#A4C639" aria-hidden="true"></i>
  <% elsif @reviews.first.account.twitter? %>
    <i class="fa fa-twitter fa-4x" style="color:#0084b4" aria-hidden="true"></i>
  <% end %>

  <p>
    <strong>Name:</strong>
    <%= @reviews.first.account.name %>
  </p>

  <p>
    <strong>Uid:</strong>
    <%= @reviews.first.account.uid %>
  </p>

  <p>
    <strong>Keywords:</strong>
    <%= @reviews.first.account.keywords %>
  </p>

</div>
</br>
<!-- <div class="row"> -->

  <table class="table table-bordered">
    <thead>
      <tr>
        <!-- <th>Title</th> -->
        <th class="col-md-8">Review</th>
        <th class="col-md-2">Rating</th>
        <th class="col-md-2">Author</th>
      </tr>
    </thead>

    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <%= link_to review do %>
            <!-- <td><%= review.title %></td> -->
            <td><%= review.description %></td>
            <td>
              <div class="row" style="text-align: center">
                <% (1..review.rating.to_i).each do |r| %>
                  <i class="fa fa-star" style="color:#ffd11c"></i>
                <% end %>
              </div>
            </td>
            <td><%= review.author %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

<!-- </div> -->

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Author:</strong>
  <%= @review.author %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>