config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#home'
  get 'dashboard' => 'dashboards#index'

  get 'dashboard/projects' => 'dashboards#projects'
  resources :projects
  resources :accounts
  resources :reviews
  resources :issues


  resources :accounts do
    member do
      get :sync_reviews
    end
  end

   resources :projects do
    member do
      get :sync_issues
    end
  end
end

app/models/account.rb
require 'custom_error'

class Account < ApplicationRecord
  REVIEW_SYNC_PAGES_COUNT = 2

  validates :uid, presence: true
  validates :kind, presence: true

  belongs_to :project
  has_many :reviews, dependent: :destroy

  enum kind: { android: 0, ios: 1, twitter: 2, facebook: 3, other: 4 }

  before_save :set_account_info


  def set_account_info
    info = if android?
      GooglePlayUtils.app_info(self)
    elsif twitter?
      twitter_client = TwitterUtils.new
      twitter_client.app_info(self)
    end

    self.name = info[:name]
    self.display_picture_url = info[:display_picture_url]
  end

  def sync_reviews(total_pages=REVIEW_SYNC_PAGES_COUNT)
    if android?
      (0..(total_pages-1)).each do |page|
        begin
          remote_reviews = GooglePlayUtils.fetch_reviews(self, page)
        rescue Errors::CustomError => e
          return reviews # stop syncing reviews
        end
        remote_reviews.each do |remote_review|
          Review.sync(remote_review)
        end
      end
      reviews
    elsif twitter?
      twitter_client = TwitterUtils.new
      remote_reviews = twitter_client.fetch_mentions(self)
      remote_reviews.each do |remote_review|
        Review.sync(remote_review)
      end
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  layout 'dashboard/main'
  before_action :set_account, only: [:show, :edit, :update, :destroy, :sync_reviews]

  # GET /accounts
  def index
    @accounts = current_user.accounts
  end

  # GET /accounts/1
  def show
    # @chart_data = {}

    # @account.reviews.each do |r|
    #   @chart_data[r.created_at] = r.rating
    # end
    if @account.android?
      @chart_data = @account.reviews.group(:created_at).average(:rating)
    else
      @chart_data = {}
      @account.reviews.each do |r|
        @chart_data[r.created_at] = r.sentiment.to_f
      end
    end
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  #PATCH/PUT /accounts/1/sync_reviews
  def sync_reviews
  @account.sync_reviews
      redirect_to @account, notice: 'Account was successfully synced.'

  end

  # PATCH/PUT /accounts/1
  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def account_params
      params.require(:account).permit(:name, :slug, :uid, :keywords, :kind, :project_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="col-sm-6">
  <%= form_for(account) do |f| %>
    <% if account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

        <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :project %>
      <%= f.collection_select :project_id, Project.order(:name),:id,:name, include_blank: true %>
    </div>

    <div class="field">
      <%= f.label :uid %>
      <%= f.text_field :uid, class: 'form-control'  %>
    </div>

    <div class="field">
      <%= f.label :keywords %>
      <%= f.text_field :keywords, class: 'form-control'  %>
    </div>

    <div class="field">
      <%= f.label :kind %>
      <%= f.select :kind, Account.kinds.keys.to_a %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Accounts</h4>
</br>
  <% @accounts.each do |account| %>
    <%= link_to account do %>
      <div class="row">
        <div class="well col-md-4">
          <div class="col-md-4">
            <% if account.android? %>
              <i class="fa fa-android fa-4x" style="color:#A4C639" aria-hidden="true"></i>
            <% elsif account.twitter? %>
              <i class="fa fa-twitter fa-4x" style="color:#0084b4" aria-hidden="true"></i>
            <% end %>
          </div>
          <div class="col-md-8">
            <p class="row"><%= account.name %></p>
            <p class="row"><%= account.uid %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>
<% if @account.android? %>
  <i class="fa fa-android fa-4x" style="color:#A4C639" aria-hidden="true"></i>
<% elsif @account.twitter? %>
  <i class="fa fa-twitter fa-4x" style="color:#0084b4" aria-hidden="true"></i>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @account.uid %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @account.keywords %>
</p>
<%= link_to 'Sync Reviews', sync_reviews_account_path(@account) %> |
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>
</br>

</br>
</br>
<%= line_chart @chart_data, ytitle: 'rating' %>
</br>
</br>
</br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <!-- <th>Title</th> -->
        <th class="col-md-8">Review</th>
        <th class="col-md-2">Rating/Sentiment</th>
        <th class="col-md-2">Author</th>
      </tr>
    </thead>

    <tbody>
      <% @account.reviews.each do |review| %>
        <tr>
          <%= link_to review do %>
            <!-- <td><%= review.title %></td> -->
            <td><%= review.description %></td>
            <td>
             <% if @account.android? %>
                <div class="row" style="text-align: center">
                  <% (1..review.rating.to_i).each do |r| %>
                    <i class="fa fa-star" style="color:#ffd11c"></i>
                  <% end %>
                </div>
              <% else %>
                <%= review.sentiment.to_f.round(2) %>
              <% end %>
            </td>
            <td><%= review.author %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>